FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=production

# Використовуємо npm ci для надійної збірки (потребує package-lock.json)
COPY package*.json ./
RUN npm ci

COPY . .

# Передаємо змінні для Next.js (вони вшиваються в JS при білді)
ARG NEXT_PUBLIC_STRAPI_URL
ARG NEXT_PUBLIC_STRAPI_API_TOKEN
ARG NEXT_PUBLIC_MEDIA_LIBRARY_URL

RUN npm run build

EXPOSE 3000
# Next.js за замовчуванням слухає 3000, але ми підстрахуємося
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "run", "start"]