FROM node:20-alpine
WORKDIR /app

# Повертаємо стандартний production
ENV NODE_ENV=production

COPY package*.json ./
# Встановлюємо ВСІ залежності, включаючи devDependencies, 
# але в режимі production (це заставить npm поставити TS для білду)
RUN npm install --include=dev

COPY . .

# Прокидаємо ARG для білду
ARG NEXT_PUBLIC_STRAPI_URL
ARG NEXT_PUBLIC_STRAPI_API_TOKEN
ARG NEXT_PUBLIC_MEDIA_LIBRARY_URL

RUN npm run build