import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/styles/globals.css';
import Navbar from '@/components/navbar';
import { getCategoriesTree, getNavbar } from '@/services/navbar.service';
import { normalizeMenu } from '@/utils/menu';
import Footer from '@/components/footer';
import { getDictionary } from '@/services/dictionary.service';
import { ToastContainer } from 'react-toastify';
import { Analytics } from '@vercel/analytics/next';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dictionaryPromise = getDictionary();
  const navBarPromise = getNavbar('main_menu');
  const footerMenuPromise = getNavbar('footer');
  const categoriesPromise = getCategoriesTree();
  const dictionary = await dictionaryPromise;
  const navBar = await navBarPromise;
  const footerMenu = await footerMenuPromise;
  const categoriesTree = await categoriesPromise;
  const menu = normalizeMenu(navBar, categoriesTree);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar menu={menu} dictionary={dictionary} />
        <main className="container pt-32 min-h-[calc(100vh-68px)] flex flex-col">
          {children}
        </main>
        <Footer dictionary={dictionary} menu={footerMenu} />
        <ToastContainer />
        <Analytics />
      </body>
    </html>
  );
}
