import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/styles/globals.css';
import Navbar from '@/components/navbar';
import { getCategoriesTree, getNavbar } from '@/services/navbar.service';
import { normalizeMenu } from '@/utils/menu';
import Footer from '@/components/footer';
import { getDictionary } from '@/services/dictionary.service';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dictionary = await getDictionary();
  const navBarPromise = getNavbar('main_menu');
  const categoriesPromise = getCategoriesTree();
  const navBar = await navBarPromise;
  const categoriesTree = await categoriesPromise;
  const menu = normalizeMenu(navBar, categoriesTree);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar menu={menu} dictionary={dictionary} />
        <main className="container pt-20">
          {children}
          <Footer dictionary={dictionary} />
        </main>
      </body>
    </html>
  );
}
