export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  PROFILE: '/profile',
  ABOUT: '/about',
  CONSULTING_AND_NETWORKING: '/consulting-and-networking',
  TESTIMONIALS: '/testimonial',
  CONTACTS: '/contacts',
  ALL_COURSES: '/all-courses',
  COURSES: '/courses',
  QUESTIONS: '/questions',
  USER_COURSES: '/user-courses',
  RESULTS: '/results',
  HOME: '/homepage',
  DICTIONARY: '/dictionary',
  CERTIFICATES: '/certificates',
};
